### ISSUE TITLE
bug in a partial block processing

### ISSUE THREAD

**Issue by yauhen-arnatovich** [horrorho/Java-XTS-AES#1]
Hi Guys,

I tried NIST XTS test vectors with your code. Not all tests have passed.
The problem with the partial block processing. In particular, your code does not perform stealing of *bits* when data unit length is not multiple 8 bits, i.e., not a full byte. 
Your current implementation assumes that the data unit length is *always* multiple of 8 bits, and thus it only performs *bytes* stealing (if needed). 

For example, your code works if data unit length is 200 bits, i.e., input data length is full 25 bytes. However, size of 25 bytes is not multiple of 16, so your code will do *bytes* stealing in this case.

But, if data unit length is 250 bits, i.e., 31.25 bytes, where 31 bytes are full, and the last 32nd byte is not full. This last byte is padded with '0' to be full (according to NIST description of test vectors preparation). The padded bits in that particular padded byte should be replaced by applying *bits* stealing. 

In fact, data unit lengths such as 130, 140, and 250 (all used by NIST) are not handled by your current implementation so that all such test vectors failed to pass.

According to the XTS-AES Validation System, the successful completion of the tests is required
to be validated as conforming to the XTS-AES algorithm standard.

Please, take a note of this issue.
FYI @horrorho 

Thank you.

**Comment by horrorho** [comment]
Hi. Thank you for the input.

It's not really a bug, it's just that non byte aligned data is unsupported. However I have failed to document this clearly. I'll amend this.

This project is based on the IEEE P1619 DRAFT proposals as clearly stated on the home page along with a warning to such effect. I've made no claims to any sort of NIST conformance.

That being said we can cite NIST publications:

_The XTS-AES Validation System (XTSVS) : 6.2 The XTSGenAES Test_
`An implementation may support a data unit length that is not a multiple of 8 bits.`

_Recommendation for Block Cipher Modes of Operation: The XTS-AES Mode for Confidentiality on Storage Devices : 4 Conformance_
`...an implementation of XTS-AES may further restrict the length of the data units for any key.`

So unless I'm mistaken and I admit that I've only partially skimmed the above NIST documentations, implementations that restrict data units to multiples of 8 bits are permitted.

Also unless I'm mistaken, your question revolves around:
- NIST conformance.
- Non-byte aligned data.

NIST conformance: Undefined. I'll make a note to this effect.

Non byte aligned data: I have no plans to support this. I'll make a note to this effect.
